
package ec.edu.ups.interfaz;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PanelDibujo extends JPanel {

    private int opcion;

    /**
     * Creates new form PanelDibujo
     */
    public PanelDibujo() {
        initComponents();
        opcion = 0;
    }

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;

        g.setColor(Color.YELLOW);
        g.fillOval(5, 20, 150, 150);
        g2.setStroke(new BasicStroke(4.0f));
        g.setColor(Color.CYAN);
        g.drawOval(5, 20, 150, 150);
//      SORPRENDIDO
        if (opcion == 1) {
            g.drawString("Sorprendido", 55, 15);
            g.setColor(Color.WHITE);
            g.fillOval(35, 30, 40, 60);
            g.fillOval(85, 30, 40, 60);
            g.fillOval(40, 120, 80, 30);

            g.setColor(Color.BLACK);
            g.fillOval(75, 80, 20, 10);
            g.fillOval(50, 40, 15, 20);
            g.fillOval(100, 40, 15, 20);
            g2.setStroke(new BasicStroke(3.0f));
            g.drawOval(40, 120, 80, 30);
        }

//      CHINO
        if (opcion == 2) {
            g.drawString("CHINITO", 55, 15);
            g.setColor(Color.BLACK);
            g2.setStroke(new BasicStroke(2.0f));
            g.fillOval(75, 80, 20, 10);
            g.drawLine(40, 30, 45, 35);
            g.drawLine(50, 30, 55, 35);
            g.drawLine(60, 30, 65, 35);
            g.drawLine(70, 30, 75, 35);
            g.drawLine(80, 30, 85, 35);
            g.drawLine(90, 30, 95, 35);
            g.drawLine(100, 30, 105, 35);
            g.drawLine(110, 30, 115, 35);
            g2.setStroke(new BasicStroke(5.0f));
            g.drawArc(30, 25, 50, 50, -45, -90);
            g.drawArc(95, 25, 50, 50, -45, -90);
            g.drawArc(20, 100, 120, 120, 120, -65);

        }

//      FELIZ
        if (opcion == 3) {
            g.drawString("FELIZ", 55, 15);
            g.setColor(Color.WHITE);
            g.fillOval(35, 30, 40, 60);
            g.fillOval(85, 30, 40, 60);
            g.setColor(Color.BLACK);
            g.fillOval(75, 80, 20, 10);
            g.fillOval(45, 45, 20, 20);
            g.fillOval(95, 45, 20, 20);
            g2.setStroke(new BasicStroke(5.0f));
            g.drawArc(30, 25, 100, 100, -45, -90);

        }

//      TRISTE
        if (opcion == 4) {
            g.drawString("TRISTE", 55, 15);
            g.setColor(Color.WHITE);
            g.fillOval(35, 30, 40, 60);
            g.fillOval(85, 30, 40, 60);
            g.setColor(Color.BLACK);
            g.fillOval(55, 55, 20, 25);
            g.fillOval(75, 80, 10, 15);
            g.fillOval(85, 55, 20, 25);
            g2.setStroke(new BasicStroke(5.0f));
            g.drawArc(20, 100, 120, 120, 120, -65);
        }

//     ENOJADO
        if (opcion == 5) {
            g.drawString("ENOJADO", 55, 15);
            g.setColor(Color.WHITE);
            g.fillOval(35, 30, 40, 60);
            g.fillOval(85, 30, 40, 60);
            g.setColor(Color.BLACK);
            g.fillOval(75, 80, 10, 15);
            g.fillOval(60, 55, 15, 20);
            g.fillOval(85, 55, 15, 20);
            g2.setStroke(new BasicStroke(5.0f));
            g.drawArc(45, 40, 25, 20, 10, 90);
            g.drawArc(82, 40, 25, 20, 80, 90);
            g.drawArc(20, 100, 120, 120, 120, -65);
        }

//   LLORANDO
        if (opcion == 6) {
            g.drawString("LLORANDO", 55, 15);
            g.setColor(Color.WHITE);
            g.fillOval(35, 30, 40, 60);
            g.fillOval(85, 30, 40, 60);
            g.setColor(Color.CYAN);
            g.fillOval(65, 90, 5, 10);
            g.fillOval(45, 90, 5, 10);
            g.fillOval(115, 90, 5, 10);
            g.fillOval(95, 90, 5, 10);
            g.setColor(Color.BLACK);
            g.fillOval(75, 80, 10, 15);
            g.fillOval(95, 45, 20, 25);
            g.fillOval(45, 45, 20, 25);
            g2.setStroke(new BasicStroke(5.0f));
            g.drawArc(35, 105, 100, 100, 40, 95);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


