
package ec.edu.ups.interfaz;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu2 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelDibujo2 = new ec.edu.ups.interfaz.PanelDibujo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        caraFelizMenuItem = new javax.swing.JMenuItem();
        caraTristeMenuItem = new javax.swing.JMenuItem();
        caraEnojadaMenuItem = new javax.swing.JMenuItem();
        caraSorprendidaMenuItem = new javax.swing.JMenuItem();
        caraLlorandoMenuItem = new javax.swing.JMenuItem();
        caraChinitaMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        salirMenuItem = new javax.swing.JMenuItem();

        menuBar1.setName("");

        menu2.setLabel("File");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        menuBar1.add(menu2);

        menu4.setLabel("Edit");
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });
        menuBar1.add(menu4);

        menuBar1.getAccessibleContext().setAccessibleName("Caras");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelDibujo2Layout = new javax.swing.GroupLayout(panelDibujo2);
        panelDibujo2.setLayout(panelDibujo2Layout);
        panelDibujo2Layout.setHorizontalGroup(
            panelDibujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        panelDibujo2Layout.setVerticalGroup(
            panelDibujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDibujo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDibujo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Caras");

        caraFelizMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        caraFelizMenuItem.setText("Feliz");
        caraFelizMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraFelizMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraFelizMenuItem);

        caraTristeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        caraTristeMenuItem.setText("Triste");
        caraTristeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraTristeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraTristeMenuItem);

        caraEnojadaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        caraEnojadaMenuItem.setText("Enojada");
        caraEnojadaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraEnojadaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraEnojadaMenuItem);

        caraSorprendidaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        caraSorprendidaMenuItem.setText("Sorprendida");
        caraSorprendidaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraSorprendidaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraSorprendidaMenuItem);

        caraLlorandoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        caraLlorandoMenuItem.setText("Llorando");
        caraLlorandoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraLlorandoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraLlorandoMenuItem);

        caraChinitaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        caraChinitaMenuItem.setText("Chinita");
        caraChinitaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caraChinitaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(caraChinitaMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(salirMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu4ActionPerformed

    private void caraFelizMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraFelizMenuItemActionPerformed
        panelDibujo2.setOpcion(3);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraFelizMenuItemActionPerformed

    private void caraTristeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraTristeMenuItemActionPerformed
        panelDibujo2.setOpcion(4);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraTristeMenuItemActionPerformed

    private void caraEnojadaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraEnojadaMenuItemActionPerformed
        // TODO add your handling code here:
        panelDibujo2.setOpcion(5);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraEnojadaMenuItemActionPerformed

    private void caraSorprendidaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraSorprendidaMenuItemActionPerformed
        // TODO add your handling code here:
        panelDibujo2.setOpcion(1);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraSorprendidaMenuItemActionPerformed

    private void caraChinitaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraChinitaMenuItemActionPerformed
        // TODO add your handling code here:
        panelDibujo2.setOpcion(2);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraChinitaMenuItemActionPerformed

    private void caraLlorandoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caraLlorandoMenuItemActionPerformed
        // TODO add your handling code here:
        panelDibujo2.setOpcion(6);
        panelDibujo2.repaint();
    }//GEN-LAST:event_caraLlorandoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem caraChinitaMenuItem;
    private javax.swing.JMenuItem caraEnojadaMenuItem;
    private javax.swing.JMenuItem caraFelizMenuItem;
    private javax.swing.JMenuItem caraLlorandoMenuItem;
    private javax.swing.JMenuItem caraSorprendidaMenuItem;
    private javax.swing.JMenuItem caraTristeMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Menu menu2;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private ec.edu.ups.interfaz.PanelDibujo panelDibujo2;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables
}
